const FILTER_ALL = 'FILTER_ALL';
const FILTER = 'FILTER';
const GET_SEARCH_ID = 'GET_SEARCH_ID';
const GET_TICKETS = 'GET_TICKETS';
const UPDATE_TICKETS_WITH_FILTER = 'UPDATE_TICKETS_WITH_FILTER';
const UPDATE_TICKETS_WITH_TABS = 'UPDATE_TICKETS_WITH_TABS';
const SHOW_TICKETS = 'SHOW_TICKETS';
const TABS = 'TABS';

export {
  FILTER_ALL,
  FILTER,
  GET_SEARCH_ID,
  GET_TICKETS,
  UPDATE_TICKETS_WITH_FILTER,
  UPDATE_TICKETS_WITH_TABS,
  SHOW_TICKETS,
  TABS,
};
