const FILTER_ALL = 'FILTER_ALL';
const FILTER = 'FILTER';
const GET_SEARCH_ID = 'GET_SEARCH_ID';
const GET_TICKETS = 'GET_TICKETS';
const SHOW_TICKETS = 'SHOW_TICKETS';
const TABS = 'TABS';

export { FILTER_ALL, FILTER, GET_SEARCH_ID, GET_TICKETS, SHOW_TICKETS, TABS };
